version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: blog-api
    stdin_open: true
    volumes:
      - ./:/go/app/src
    ports:
     - 8000:8080
    depends_on:
     - mysql
  mysql:
    image: mysql:8.0
    container_name: db-api
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: pass